---
- name: Make sure python3 is installed
  apt:
    name: python3
    state: present
    update_cache: yes
- name: Make sure pip is installed
  apt:
    name: python3-pip
    state: present
    update_cache: yes
- name: Make sure docker-py is installed 
  pip:
    name: docker-py
- name: Create Docker volume for nodered
  docker_volume:
    name: "{{ nodered_volume }}"
- name: Run nodered
  docker_container:
    name: nodered
    image: "{{ nodered_image }}"
    ports:
      - "{{ nodered_port }}:1880"
    state: started
    restart_policy: always
    volumes:
      - "{{ nodered_volume }}"