---
name: Deploy to Ansible Galaxy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Ansible Galaxy Role Import
        uses: 0x022b/galaxy-role-import-action@1.0.0
        with:
          api_key: ${{ secrets.GALAXY_API_KEY }}